project:
  type: website
  output-dir: docs

website:
  title: "David Villalobos Hornback"
  navbar: 
    left:
      - href: index.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: projects.qmd  # <-- add this
        text: My Projects   # <-- add this
      - href: Hobbies &amp; Interests.qmd
        text: Hobbies & Interests
format:
  html:
    theme:
      - superhero
      - brand
    css: styles.css
    toc: true



